### ISSUE TITLE
Encrypt HTTP auth passwords

### ISSUE THREAD

**Issue by vabatta** [jfroment/seedbox#25]
Hi, it took me a while to figure out that you need to encrypt auth HTTP passwords in file using something like `htpasswd` from the `apache2-utils` package, according to the [traefik docs](https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/#general).

[This line should be changed](https://github.com/jfroment/seedbox/blob/9310e4b6f82c9fd536a85fafa9e6d074f65e4bfc/update-all.sh#L19).

**Comment by joss-rendall** [comment]
Hi, mon co-patriote !!
my http_auth file created by update-all.sh like this

user
:encrypted_password

in the [trafik docs](https://doc.traefik.io/traefik/v2.0/middlewares/basicauth/#general) the file need by traefik is in one line, is it why it dosn't work in mine sever ?

**Comment by jfroment** [comment]
It seems that you have a newline at the end of the HTTP_USER variable. Maybe a bad copy/paste? Try to rewrite it and avoid copy/pastes, specially from windows which could lead to side-effects (CR/LF vs LF only in Unix world).

**Comment by joss-rendall** [comment]
thks for your response, i found the problem before, i did bad input in the .env config, i put the password clear and not with encrytion...... , it work fine in the http file.
all password in .env must be encypted ? because i can't connect in portainer.mondomaine.com admin page... i put encrypted password with double $ when necessary and no simple quote, i Test remove the --admin-password command in portainer.yaml fot acces to normaly fisrt login page for configure admin account, it dont work to..... Bad feeling...snif

**Comment by jfroment** [comment]
Only the HTTP_PASSWORD must be encrypted (and quoted), the other ones should be set non-encrypted.
Maybe that's the issue.

**Comment by jfroment** [comment]
v2.1 addressed it by adding comments in .env.sample. I'm closing this issue, but feel free to re-open if there are still questions.
