### ISSUE TITLE
Question about heimdall config

### ISSUE THREAD

**Issue by notDavid** [jfroment/seedbox#36]
Hi there, so i'm curious, could you explain what exactly you mean by "_Beware to the host when enabling it!_" in [the example config](https://github.com/jfroment/seedbox/blob/0062095ae36feec8f6f2aaca11474f4f9680e993/config.sample.yaml#L224) ?

Thank you!

**Comment by jfroment** [comment]
Hello, yes my bad the warning is maybe too vague...

In fact, in the default config file, as Heimdall is a dashboard / frontpage app, its host is set to ``${TRAEFIK_DOMAIN}`` ([here](https://github.com/jfroment/seedbox/blob/0062095ae36feec8f6f2aaca11474f4f9680e993/config.sample.yaml#L230)), and not a specific subdomain like it is the case for other apps (sonarr.example.com, deluge.example.com...). So if you enable Heimdall with the default config, Heimdall will be accessible on your parent host domain. Some people may already have a service (managed on their own) on the top-level domain so that is why there is this warning.

Note: you can obviously choose a subdomain for heimdall if you set it to something like ``dashboard.${TRAEFIK_DOMAIN}`` or ``heimdall.${TRAEFIK_DOMAIN}``.

**Comment by jfroment** [comment]
Hello again,

Yes, you figured it out perfectly. The provided default configuration works out of the box only with Wireguard. With other providers, you would have to use the correct configuration according to your needs.
