### ISSUE TITLE
Error on yq since upgrade V2

### ISSUE THREAD

**Issue by Sigri44** [jfroment/seedbox#43]
Hello,

Have upgrade soft in V2, but now have this warning :
```bash
initCommand [WARN] yq default output is now 'auto' (based on the filename extension). Normally yq would output 'props', but for backwards compatibility 'yaml' has been set. Please use -oy to specify yaml, or drop the -p flag.
```

Thx

**Comment by jfroment** [comment]
Hello, does it break something, or is everything ok still?

It is caused by https://github.com/mikefarah/yq/issues/1608, a breaking change in a recent minor version in yq.
As I do not always update my version of yq, I did not notice it. Good catch thanks.

I will specify the output format in the next release of the script, so we won't have the warning anymore.
