### ISSUE TITLE
Error response from daemon: conflicting options: port publishing and the container type network mode

### ISSUE THREAD

**Issue by Pverte** [jfroment/seedbox#50]
Heyy people !
I keep getting the error 
`Error response from daemon: conflicting options: port publishing and the container type network mode` After I run the script and when it's trying to recreate the containers. It's been 3 days that I'm looking where's the issue but I don't find anything.

Sometime I also get that it's the host and the container type network mode that is conflicting.
What should I add in the config.yaml so that it stops conflicting ?

**Comment by jfroment** [comment]
Hi!
Mmh, before I had a simple warning for this issue, now it seems that you updated docker compose and now it causes an error.
Since plex uses Host network mode, the ports binding must be removed from the yaml.
You have two options to fix it:
- use the ``dev`` branch, which has this specific fix. I'm planning to release a new version from this branch soon. It is quite stable and should not cause any issues.
- use a custom plex.yaml file, without the ports binding (remove the whole ports section from the custom yaml) and point your plex section in config.yaml to ise the custom file (refer to the documentation to do so).

Hope that helps!

**Comment by Pverte** [comment]
Okay ! I've done a custom for plex and it's working
I also want to point out that it's the same with netdata but with the hostname, I made a custom without the hostname line and now it's working !
